### ISSUE TITLE
Regexes that filter username part from the regex

### ISSUE THREAD

**Issue by Bramzor** [lorey/social-media-profiles-regexs#11]
I noticed that the regexes used do not provide username back as part of the regex. An example on how to do this is:

> (?:(?:http|https):\/\/)?(?:www.|m.)?facebook.com\/(?!home.php)(?:(?:\w)*#!\/)?(?:pages\/)?(?:[?\w\-]*\/)?(?:profile.php\?id=(?=\d.*))?([\w\.-]+)$

This allows you to filter out all the things you do not need and only return username as a result.
Wouldn't it be a good idea to take this as the standard for this repo?

Example for instagram that only returns username:
https://regex101.com/r/DBVLCq/1

(Might also be a good idea to always include a regex101.com address so people can add tests and improve regexes

**Comment by Bramzor** [comment]
Added a pull request with some improvements: #12

**Comment by lorey** [comment]
Great idea, should've done that long ago! 
* I've added named groups to all regexes now so you should be able to get usernames/ids/whatever for all links. 
* I've added pytest so all regexes are checked against all known hyperlinks automatically.

Hope this helps! Let me know what you think :raised_hands:
