### ISSUE TITLE
Support Recruiter profiles for LinkedIn

### ISSUE THREAD

**Issue by 2019342a** [lorey/social-media-profiles-regexs#14]
LinkedIn Recruiter urls do not have an `in` or `pub` on the path but `recruiter`.

**Example** : `http(s)?:\/\/([\w]+\.)?linkedin\.com\/(in|pub|recruiter)\/[A-z0-9_-]+\/?`

**Comment by lorey** [comment]
Oh, I didn't know that. Thanks!

Would you like to open a PR?

**Comment by 2019342a** [comment]
Sure, I'll do that.

**Comment by lorey** [comment]
Let's use #17 for the rest.
