### ISSUE TITLE
More  social media profiles

### ISSUE THREAD

**Issue by JamoCA** [lorey/social-media-profiles-regexs#3]
I see that there hasn't been any additions within the last 2 years.  Here are the ones that you've identified that match some of the initial regex filters I've written.  (NOTE: These also work extremely well when using the jQuery validation and adding the regex below to the `data-rule-pattern` attributes.)

**Instagram**
`^http(?:s)?:\/\/(?:www\.)?instagram\.com\/([a-zA-Z0-9_]+)$`

**Google Plus**
`^http(?:s)?:\/\/plus\.google\.com\/(.+)$`

**Pinterest**
`^http(?:s)?:\/\/(?:www\.)?pinterest\.com\/([a-zA-Z0-9_]+)$`

**Vimeo Video**
`^http(?:s)?:\/\/(?:www\.)?vimeo\.com\/(?:channels\/[0-9]+\/)?([0-9]+)$
^http(?:s)?:\/\/(?:www\.)?vine\.co\/v\/([a-zA-Z0-9_\/]+)$`

**VimeoChannel**
`^http(?:s)?:\/\/(?:www\.)?vimeo\.com\/channels\/([0-9]+)$`

**Skype**
`^skype:([a-zA-Z0-9_]+)\?call$`

**WordPress**
`^http(?:s)?:\/\/(?:[a-zA-Z0-9-]+)?.wordpress\.com\/(?!feed)(.+)?$`

**YouTube Channel**
`^http(?:s)?:\/\/(?:www\.)?youtube\.com\/channel\/(?:\w+\/)?([a-zA-Z0-9_-]+)$`

**YouTube Embed**
`^http(?:s)?:\/\/(?:www\.)?youtube.com\/embed\/([a-zA-Z0-9_-]+)$`

**YouTube User**
`^http(?:s)?:\/\/(?:www\.)?youtube\.com\/user\/(?:\w+\/)?([a-zA-Z0-9_-]+)$`

**YouTube Video**
`^http(?:s)?:\/\/(?:www\.)?youtube\.com\/(?!user)(?!channel)(?:\w+\/)?([a-zA-Z0-9_-]+)(?:\/)?$`

**YouTube Video**
`^http(?:s)?:\/\/youtu.be/([a-zA-Z0-9_-]+)$`

**StackOverflow**
`^http(?:s)?:\/\/(?:www\.)?stackoverflow\.com\/(.+)$`

**Comment by lorey** [comment]
Thanks so much!

**Comment by glefait** [comment]
I spend few hours to build a lib because I was facing the same needs, here is it : https://github.com/glefait/social-regexes

Thank you both @JamoCA and @lorey for your work, I will used and incorporate some of these regexes.

**Comment by lorey** [comment]
Hey @JamoCA, I've given you write access to the repository, since I have not much time for this right now.. Feel free to add your suggestions without opening a pull request. Thanks for your help so far, much appreciated.

**Comment by fexell** [comment]
Thought I could share some of my regexs' for social media. They basically check for everything. This include accepted symbols in usernames and max length.

(The HTML5 patterns are actually Python regexs', but they seem to work. For me, at least).

Twitter PHP: /\A((https?:\/\/)?(www\.)?twitter\.com\/)?((@)?([a-z0-9_]{1,15}))?(\/)?/i
Twitter HTML5 Pattern: ^((https?://)?(www\.)?twitter\.com\/)?(@?([A-Za-z0-9_]{1,15}))?/?

Facebook PHP: /\A((https?:\/\/)?(www\.)?(facebook|fb)\.com\/)?(([a-z0-9._-]{1,50}))?(\/)?/i
Facebook HTML5 Pattern: ^((https?://)?(www\.)?(facebook|fb)\.com/)?([A-Za-z0-9._-]{1,50})?/?
Basically the same as twitter, but also with if "fb"-short link.

Instagram PHP: /\A((https?:\/\/)?(www\.)?(instagram\.com|instagr.am)\/)?(([a-z0-9._]{1,30}))/i
Instagram HTML5 Pattern: ^((https?://)?(www\.)?instagram\.com/)?([A-Za-z0-9._]{1,30})?/?

YouTube PHP: /\A((https?:\/\/)?(www\.)?(youtube\.com|youtu.be)\/)?(([a-z0-9]{5,20}))/i
YouTube HTML5 Pattern: ^((https?://)?(www\.)?(youtube\.com|youtu.be)/)?([A-Za-z0-9]{5,20})?/?

Snapchat PHP: /\A((https?:\/\/)?(www\.)?snapchat\.com\/)?(\/add\/)?(([a-z0-9._-]{2,16}))/i
Snapchat HTML5 Pattern: ^((https?://)?(www\.)?snapchat\.com/)?(add/)?([A-Za-z0-9._-]{1,15})?/?

If you end up using any of these, I hope they will work for y'all. Peace! :)

**Comment by lorey** [comment]
Most of the URLs you guys provided are now part of the repository. Thanks so much <3

Feel free to open another issue or PR if you have anything to add!
