### ISSUE TITLE
[QUESTION] Use or not use https as default

### ISSUE THREAD

**Issue by subversivo58** [lorey/social-media-profiles-regexs#5]
Most social networks use **https** or redirect entries on port **80** to **443** ... unknown that does not use **https** :fearful: 

In cases (obvious) where the service uses https but the user informs http ... the link may even be correct because it points to a valid endpoint once the application server redirects it, however in my opinion (not based on a normalization) the regex should fail (deny)

The GitHub for example (the regex) in my view is incorrect because the site itself does not transmit data if not by **https** and the **www** subdomain is not used

    // how are you now
    http(s)?:\/\/(www\.)?github\.com/[A-z 0-9 _ -]+\/?
    
    // perhaps a more correct approach
    https:\/\/github\.com/[a-zA-Z0-9_-]+\/?

**Comment by lorey** [comment]
Hey @subversivo58,
thanks for the issue. It totally see your point. I guess it depends on your goal with these regexes. For scraping, I'd say it's the first one since you want to get all possible user accounts, even if the url ist wrong(ish). Of course, this depends on your use case. What would be your use case for only fetching correct ones with https and without www?

**Comment by subversivo58** [comment]
I do not have a specific use case I just made a remark when I used the GitHub example.

I could have made another remark: Pinterest and Instagram use **www** soon could be:

    https:\/\/www\.instagram\.com\/[a-zA-Z0-9_]+\/?
    // and
    https:\/\/www\.pinterest\.com\/[a-zA-Z0-9_]+\/?

PS: I got here (in this repo) looking for a regex for StackOverflow (SO and SOpt) for use in `javascript` `.test()` like:

    /https:\/\/(pt\.)?stackoverflow\.com\/users\/[\d]{4,11}\/[a-z-]/g.test(url)

I know that the approach is a personal matter and that there is no standardization but for example it is not accessed **http://www.github.com/any-user** this will redirect to **https://github.com/any-user** as soon as validate a url that does not even exist that it can be redirected to a valid endpoint in my opinion is not correct

**Comment by lorey** [comment]
I get that. But like I explained above, IMHO it's not about whether it is correct or not but whether it works for the given use case. Also services could switch from www version to non-www version. What are you gonna do? Change the regex so old URLs don't match anymore or simply still match both as long as they return a URL that can be resolved? That is why all these regexes should match a superset of the urls, it's [defensive programming](https://en.wikipedia.org/wiki/Defensive_programming) . Mostly based on URLs I have actually seen in the wild. As long as the URL redirects to the correct URL, which is mostly the case, nothing keeps you from just making an http request and checking the result to get the valid url.

Thanks for your input, feel free to open a PR or another issue if you would like to discuss anything else.
