### ISSUE TITLE
not mandatory for protocol part and www(host Name) in regex

### ISSUE THREAD

**Issue by AKArunkumar** [lorey/social-media-profiles-regexs#6]
Regex should include protocol and host Name part as Option not mandatory 
Example: 
(http(s)?:\/\/[\w]+\.)?linkedin\.com\/in\/(A-z 0-9 _ -)\/?

**Comment by yeganemehr** [comment]
Hey @AKArunkumar 

I agree to optional www (most of regular expressions in this repo really doesn't care about first subdomain) but not about protocol.
In your opinion ftp://github.com/AKArunkumar is a valid social profile?

**Comment by AKArunkumar** [comment]
I trying for linkedin profile URL check. I am not able to validate any personal profiles and altered regex

`/((http|https):\/\/?(?:www\.)?)?linkedin.com\/in\/(\w+:{0,1}\w*@)?(\S+)(:([0-9])+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?\/?/;`

This one working good.

**Comment by lorey** [comment]
Hey you two. Was not aware of this before. Wil fix.

**Comment by lorey** [comment]
For anyone interested, here's some background information: https://stackoverflow.com/a/9632363/1275778
